POST http://localhost:3001/categories
Content-Type: application/json

{
    "categoryName":"Ice Cream",
    "image":"https://img.freepik.com/free-photo/colorful-tasty-donuts_144627-18316.jpg",
    "description":"Indulge in our creamy, delicious ice cream flavors today and treat yourself to a sweet escape from the heat. Our handcrafted, premium ice cream is made with only the freshest ingredients and is sure to satisfy your sweet tooth.",
    "products":[
        "640796ad2b9fafb98811fe7d",
        "640797392b9fafb98811fe80",
        "640797b02b9fafb98811fe83"
    ]
}

###

POST  http://localhost:3001/products
Content-Type: application/json

{
    "name":"Caramel donut",
    "description": "Caramel donuts are coated in a smooth and creamy caramel glaze, made from caramelized sugar and cream. This glaze gives the donut a rich and buttery flavor with a sweet and slightly salty finish. They are a popular treat for those who enjoy sweet and indulgent pastries, and they pair well with a cup of coffee or tea for a satisfying snack or breakfast.",
    "image":"public/images/slide5.jpg",
    "price": 3,
    "categoryId": "640f80e0c2b45987a3b4fb99",
    "isTop": true
}

