POST http://localhost:3001/categories
Content-Type: application/json

{
    "categoryName":"Ice Cream",
    "image":"https://img.freepik.com/free-photo/colorful-tasty-donuts_144627-18316.jpg",
    "description":"Indulge in our creamy, delicious ice cream flavors today and treat yourself to a sweet escape from the heat. Our handcrafted, premium ice cream is made with only the freshest ingredients and is sure to satisfy your sweet tooth.",
    "products":[
        "640796ad2b9fafb98811fe7d",
        "640797392b9fafb98811fe80",
        "640797b02b9fafb98811fe83"
    ]
}

###

POST  http://localhost:3001/products
Content-Type: application/json

{
    "name":"Caramel ice cream",
    "description": "This caramel ice cream is a decadent treat that is sure to satisfy any sweet tooth. Its silky texture and luscious caramel flavor make it a great choice for a special dessert or an indulgent snack.",
    "image":"images/caramelIce.jpg",
    "price": 12,
    "categoryId": "64072ceabe7077040b8c2350",
    "isTop": true
}

