POST http://localhost:3001/users
Content-Type: application/json

{
    "firstName":"Davor",
    "lastName": "Maric",
    "username": "davorm",
    "email":"davor@gmail.com",
    "password":"pavlemarko5582"
}